// Pre-built block arrays for all built-in templates
// Used by the admin editor to pre-populate the block editor when editing a built-in template
// The user can then modify these blocks and save as a custom override

const BUILTIN_BLOCKS = {

    // ══════════════════════════════════════════
    //  GST TEMPLATES
    // ══════════════════════════════════════════

    gst_noc: [
        { type: 'heading', content: 'NO OBJECTION CERTIFICATE', style: { bold: true, center: true, size: 32, underline: true } },
        { type: 'blank', spacing: 200 },
        { type: 'text', content: 'Date: {{nocDate|date}}', style: { size: 24 } },
        { type: 'text', content: 'Place: {{nocPlace}}', style: { size: 24 } },
        { type: 'blank', spacing: 200 },
        { type: 'text', content: 'To Whom So Ever It May Concern', style: { bold: true, size: 26 } },
        { type: 'blank', spacing: 200 },
        { type: 'text', content: 'Subject: No Objection Certificate for {{nocPurpose}} of {{entityName}}', style: { size: 24 } },
        { type: 'blank', spacing: 100 },
        { type: 'text', content: 'Respected Sir/Madam,', style: { size: 24 } },
        { type: 'blank', spacing: 100 },
        { type: 'text', content: 'I, {{propertyOwnerName}}, S/o / D/o / W/o {{propertyOwnerRelation}}, bearing PAN {{propertyOwnerPan}} and Aadhar No. {{propertyOwnerAadhar}}, owner of the property situated at {{propertyAddress}}, hereby state that I have no objection if {{fullName}}, bearing PAN {{pan}} and Aadhar No. {{aadhar}}, carrying on business under the trade name "{{tradeName}}" (GSTIN: {{gstNumber}}) uses the above-mentioned premises for the purpose of {{nocPurpose}}.', style: { size: 24 } },
        { type: 'blank', spacing: 100 },
        { type: 'text', content: 'I confirm that the above information is true and correct to the best of my knowledge and belief.', style: { size: 24 } },
        { type: 'blank', spacing: 300 },
        { type: 'text', content: 'Yours faithfully,', style: { size: 24 } },
        { type: 'signatureBlock', lines: ['____________________________', 'Name: {{propertyOwnerName}}', 'PAN: {{propertyOwnerPan}}', 'Aadhar: {{propertyOwnerAadhar}}', '(Property Owner)'], style: {} }
    ],

    gst_rental_agreement: [
        { type: 'heading', content: 'RENTAL AGREEMENT', style: { bold: true, center: true, size: 32, underline: true } },
        { type: 'blank', spacing: 200 },
        { type: 'text', content: 'This Rental Agreement is executed on this {{agreementDate|date}} at {{agreementPlace}}', style: { size: 24 } },
        { type: 'blank', spacing: 100 },
        { type: 'text', content: 'BETWEEN', style: { bold: true, center: true, size: 24 } },
        { type: 'blank', spacing: 100 },
        { type: 'text', content: '{{landlordName}}, S/o / D/o / W/o {{landlordFatherName}}, residing at {{landlordAddress}} (Aadhar: {{landlordAadhar}}) (PAN: {{landlordPan}})', style: { size: 24 } },
        { type: 'text', content: '(Hereinafter referred to as the "LANDLORD", which expression shall include his/her heirs, executors, and assigns)', style: { italics: true, size: 22 } },
        { type: 'blank', spacing: 100 },
        { type: 'text', content: 'AND', style: { bold: true, center: true, size: 24 } },
        { type: 'blank', spacing: 100 },
        { type: 'text', content: '{{entityName}} ({{entityType}}) (CIN: {{cin}}) (GSTIN: {{gstNumber}}), having its registered office at {{registeredAddress}}, represented by {{tenantAuthorizedPerson}}, {{tenantDesignation}}', style: { size: 24 } },
        { type: 'text', content: '(Hereinafter referred to as the "TENANT", which expression shall include its successors and assigns)', style: { italics: true, size: 22 } },
        { type: 'blank', spacing: 100 },
        { type: 'text', content: 'The Landlord and Tenant are collectively referred to as "Parties" and individually as "Party".', style: { size: 24 } },
        { type: 'blank', spacing: 100 },
        { type: 'text', content: 'WHEREAS the Landlord is the absolute owner of the property more fully described hereunder and has agreed to let out the same to the Tenant on the terms and conditions mentioned below:', style: { size: 24 } },
        { type: 'blank', spacing: 100 },
        { type: 'text', content: '1. PREMISES:', style: { bold: true, size: 24 } },
        { type: 'text', content: 'The Landlord hereby lets out the premises situated at {{propertyAddress}} (hereinafter referred to as the "Premises") to the Tenant for commercial/official use.', style: { size: 24 } },
        { type: 'blank', spacing: 100 },
        { type: 'text', content: '2. PERIOD OF TENANCY:', style: { bold: true, size: 24 } },
        { type: 'text', content: 'The tenancy shall be for a period of {{agreementPeriod}} months commencing from {{agreementDate|date}}, unless terminated earlier by either party.', style: { size: 24 } },
        { type: 'blank', spacing: 100 },
        { type: 'text', content: '3. MONTHLY RENT:', style: { bold: true, size: 24 } },
        { type: 'text', content: 'The Tenant shall pay a monthly rent of Rs. {{monthlyRent}}/- (Rupees {{monthlyRent|words}} Only) to the Landlord, payable on or before the 5th day of every succeeding month.', style: { size: 24 } },
        { type: 'blank', spacing: 100 },
        { type: 'text', content: '4. SECURITY DEPOSIT:', style: { bold: true, size: 24 } },
        { type: 'text', content: 'The Tenant has deposited a sum of Rs. {{securityDeposit}}/- (Rupees {{securityDeposit|words}} Only) as security deposit with the Landlord, which shall be refundable without interest at the time of vacating the premises, after adjusting any outstanding dues.', style: { size: 24 } },
        { type: 'blank', spacing: 100 },
        { type: 'text', content: '5. USE OF PREMISES:', style: { bold: true, size: 24 } },
        { type: 'text', content: 'The Tenant shall use the premises solely for commercial/official purposes and shall not use the same for any unlawful activity.', style: { size: 24 } },
        { type: 'blank', spacing: 100 },
        { type: 'text', content: '6. MAINTENANCE:', style: { bold: true, size: 24 } },
        { type: 'text', content: 'The Tenant shall maintain the premises in good and habitable condition and shall not make any structural alterations without the prior written consent of the Landlord.', style: { size: 24 } },
        { type: 'blank', spacing: 100 },
        { type: 'text', content: '7. TERMINATION:', style: { bold: true, size: 24 } },
        { type: 'text', content: 'Either party may terminate this agreement by giving one month prior written notice to the other party. Upon termination, the Tenant shall vacate the premises peacefully and hand over possession to the Landlord.', style: { size: 24 } },
        { type: 'blank', spacing: 100 },
        { type: 'text', content: '8. GOVERNING LAW:', style: { bold: true, size: 24 } },
        { type: 'text', content: 'This agreement shall be governed by and construed in accordance with the laws of India.', style: { size: 24 } },
        { type: 'blank', spacing: 200 },
        { type: 'text', content: 'IN WITNESS WHEREOF, the parties have set and subscribed their hands on the day, month, and year first above written.', style: { size: 24 } },
        { type: 'blank', spacing: 300 },
        { type: 'text', content: 'LANDLORD                                        TENANT', style: { bold: true, size: 24 } },
        { type: 'blank', spacing: 200 },
        { type: 'text', content: 'Signature: ____________________              Signature: ____________________', style: { size: 24 } },
        { type: 'text', content: 'Name: {{landlordName}}                       Name: {{tenantAuthorizedPerson}}', style: { size: 24 } },
        { type: 'text', content: 'Aadhar: {{landlordAadhar}}                    Designation: {{tenantDesignation}}', style: { size: 24 } },
        { type: 'text', content: '                                                    For: {{entityName}}', style: { size: 24 } },
        { type: 'blank', spacing: 300 },
        { type: 'text', content: 'WITNESSES:', style: { bold: true, size: 24 } },
        { type: 'text', content: '1. Name: ____________________  Signature: ____________________', style: { size: 24 } },
        { type: 'text', content: '   Address: ________________________________________________', style: { size: 24 } },
        { type: 'blank', spacing: 100 },
        { type: 'text', content: '2. Name: ____________________  Signature: ____________________', style: { size: 24 } },
        { type: 'text', content: '   Address: ________________________________________________', style: { size: 24 } },
    ],

    gst_authorization: [
        { type: 'heading', content: 'AUTHORIZATION LETTER', style: { bold: true, center: true, size: 32, underline: true } },
        { type: 'blank', spacing: 200 },
        { type: 'text', content: 'Date: {{authDate|date}}', style: { size: 24 } },
        { type: 'text', content: 'Place: {{authPlace}}', style: { size: 24 } },
        { type: 'blank', spacing: 200 },
        { type: 'text', content: 'To Whom So Ever It May Concern', style: { bold: true, size: 26 } },
        { type: 'blank', spacing: 200 },
        { type: 'text', content: 'Subject: Authorization Letter for {{authPurpose}} of {{entityName}}', style: { size: 24 } },
        { type: 'blank', spacing: 100 },
        { type: 'text', content: 'Respected Sir/Madam,', style: { size: 24 } },
        { type: 'blank', spacing: 100 },
        { type: 'text', content: 'We, {{entityName}} (GSTIN: {{gstNumber}}), having its office at {{registeredAddress}}, hereby authorize {{authPersonName}}, bearing PAN {{authPersonPan}} and Aadhar No. {{authPersonAadhar}}, to act on our behalf for the purpose of {{authPurpose}} and to sign and submit all necessary documents, applications, and declarations in connection therewith.', style: { size: 24 } },
        { type: 'blank', spacing: 100 },
        { type: 'text', content: 'The authorized person is empowered to represent the company/firm before the GST authorities and to do all acts, deeds, and things as may be necessary for the said purpose.', style: { size: 24 } },
        { type: 'blank', spacing: 100 },
        { type: 'text', content: 'This authorization is valid until revoked in writing.', style: { size: 24 } },
        { type: 'blank', spacing: 300 },
        { type: 'text', content: 'Yours faithfully,', style: { size: 24 } },
        { type: 'signatureBlock', lines: ['____________________________', 'For {{entityName}}', 'Name: {{fullName}}', 'Designation: Director / Proprietor'], style: {} }
    ],

    // ══════════════════════════════════════════
    //  PRIVATE LIMITED (PVT) TEMPLATES
    // ══════════════════════════════════════════

    pvt_noc: [
        { type: 'heading', content: 'NO OBJECTION CERTIFICATE', style: { bold: true, center: true, size: 32, underline: true } },
        { type: 'blank', spacing: 200 },
        { type: 'text', content: 'Date: {{nocDate|date}}', style: { size: 24 } },
        { type: 'text', content: 'Place: {{nocPlace}}', style: { size: 24 } },
        { type: 'blank', spacing: 200 },
        { type: 'text', content: 'To Whom So Ever It May Concern', style: { bold: true, size: 26 } },
        { type: 'blank', spacing: 200 },
        { type: 'text', content: 'Subject: No Objection Certificate for use of premises as Registered Office of {{entityName}}', style: { size: 24 } },
        { type: 'text', content: 'Reference: CIN: {{cin}}', style: { size: 24 } },
        { type: 'blank', spacing: 100 },
        { type: 'text', content: 'I, {{propertyOwnerName}}, S/o / D/o / W/o {{propertyOwnerRelation}}, bearing PAN {{propertyOwnerPan}} and Aadhar No. {{propertyOwnerAadhar}}, am the owner/authorized occupant of the premises situated at {{propertyAddress}}.', style: { size: 24 } },
        { type: 'blank', spacing: 100 },
        { type: 'text', content: 'I hereby give my No Objection / Consent for {{entityName}} (CIN: {{cin}}) to use the above-mentioned premises as its Registered Office address as per the provisions of the Companies Act, 2013.', style: { size: 24 } },
        { type: 'blank', spacing: 100 },
        { type: 'text', content: 'I further declare that:', style: { size: 24 } },
        { type: 'text', content: '(a) I am the lawful owner/authorized occupant of the said premises.', style: { size: 24 } },
        { type: 'text', content: '(b) I have given my consent voluntarily and without any coercion.', style: { size: 24 } },
        { type: 'text', content: '(c) This NOC shall remain valid until revoked by me in writing.', style: { size: 24 } },
        { type: 'blank', spacing: 100 },
        { type: 'text', content: 'I confirm that the above information is true and correct to the best of my knowledge and belief.', style: { size: 24 } },
        { type: 'blank', spacing: 300 },
        { type: 'text', content: 'Yours faithfully,', style: { size: 24 } },
        { type: 'signatureBlock', lines: ['____________________________', 'Name: {{propertyOwnerName}}', 'PAN: {{propertyOwnerPan}}', 'Aadhar: {{propertyOwnerAadhar}}', '(Property Owner / Authorized Occupant)'], style: {} }
    ],

    pvt_dir_consent: [
        { type: 'heading', content: 'CONSENT TO ACT AS DIRECTOR', style: { bold: true, center: true, size: 28, underline: true } },
        { type: 'text', content: '(Pursuant to Section 152 of the Companies Act, 2013 and Rule 8 of the Companies (Appointment and Qualification of Directors) Rules, 2014)', style: { italics: true, center: true, size: 22 } },
        { type: 'blank', spacing: 200 },
        { type: 'text', content: 'Date: {{consentDate|date}}', style: { size: 24 } },
        { type: 'blank', spacing: 100 },
        { type: 'text', content: 'To,', style: { size: 24 } },
        { type: 'text', content: 'The Board of Directors,', style: { size: 24 } },
        { type: 'text', content: '{{entityName}}', style: { bold: true, size: 24 } },
        { type: 'text', content: '{{registeredAddress}}', style: { size: 24 } },
        { type: 'blank', spacing: 200 },
        { type: 'text', content: 'I, {{directorName}}, bearing DIN {{directorDin}}, PAN {{directorPan}} and Aadhar No. {{directorAadhar}}, residing at {{directorAddress}}, hereby give my consent to act as a Director of {{entityName}} (CIN: {{cin}}) with effect from the date of my appointment by the Board of Directors / Members of the Company.', style: { size: 24 } },
        { type: 'blank', spacing: 100 },
        { type: 'text', content: 'I further confirm that I am not disqualified from being appointed as a Director under Section 164 of the Companies Act, 2013.', style: { size: 24 } },
        { type: 'blank', spacing: 100 },
        { type: 'text', content: 'I also confirm that I have not been debarred from holding the office of Director by virtue of any order of NCLT or any other authority under any other law for the time being in force.', style: { size: 24 } },
        { type: 'blank', spacing: 300 },
        { type: 'text', content: 'Yours faithfully,', style: { size: 24 } },
        { type: 'signatureBlock', lines: ['____________________________', 'Name: {{directorName}}', 'DIN: {{directorDin}}', 'PAN: {{directorPan}}', 'Address: {{directorAddress}}'], style: {} }
    ],

    pvt_inc9: [
        { type: 'heading', content: 'DECLARATION', style: { bold: true, center: true, size: 28, underline: true } },
        { type: 'text', content: '(In terms of INC-9 — Declaration by Subscribers and First Directors)', style: { italics: true, center: true, size: 22 } },
        { type: 'blank', spacing: 200 },
        { type: 'text', content: 'Date: {{declarationDate|date}}', style: { size: 24 } },
        { type: 'blank', spacing: 200 },
        { type: 'text', content: 'I, {{declarantName}}, {{declarantDesignation}} of {{entityName}} (DIN: {{declarantDin}}), do hereby declare and confirm that:', style: { size: 24 } },
        { type: 'blank', spacing: 100 },
        { type: 'text', content: '1. I am not convicted of any offence in connection with the promotion, formation or management of any company or LLP during the last five years.', style: { size: 24 } },
        { type: 'text', content: '2. I am not an undischarged insolvent.', style: { size: 24 } },
        { type: 'text', content: '3. I have not been declared as a fugitive economic offender under Section 12 of the Fugitive Economic Offenders Act, 2018.', style: { size: 24 } },
        { type: 'text', content: '4. I have not been convicted of the offence of fraud under the Companies Act, 2013.', style: { size: 24 } },
        { type: 'text', content: '5. All the information given in the form and attachments thereto is correct and complete, and no information material to the subject matter has been suppressed or concealed.', style: { size: 24 } },
        { type: 'text', content: '6. I have complied with all the provisions of the Companies Act, 2013 and the rules made thereunder.', style: { size: 24 } },
        { type: 'blank', spacing: 300 },
        { type: 'signatureBlock', lines: ['____________________________', 'Name: {{declarantName}}', 'Designation: {{declarantDesignation}}', 'DIN: {{declarantDin}}', 'Date: {{declarationDate|date}}'], style: {} }
    ],

    pvt_specimen: [
        { type: 'heading', content: 'SPECIMEN SIGNATURE', style: { bold: true, center: true, size: 28, underline: true } },
        { type: 'blank', spacing: 200 },
        { type: 'text', content: 'Date: {{specimenDate|date}}', style: { size: 24 } },
        { type: 'blank', spacing: 200 },
        { type: 'text', content: 'I, {{signatoryName}}, {{signatoryDesignation}} of {{entityName}} (CIN: {{cin}}), hereby furnish my specimen signature as under:', style: { size: 24 } },
        { type: 'blank', spacing: 300 },
        { type: 'text', content: 'Specimen Signature:', style: { bold: true, size: 24 } },
        { type: 'blank', spacing: 100 },
        { type: 'text', content: '1. ____________________________', style: { size: 24 } },
        { type: 'blank', spacing: 100 },
        { type: 'text', content: '2. ____________________________', style: { size: 24 } },
        { type: 'blank', spacing: 100 },
        { type: 'text', content: '3. ____________________________', style: { size: 24 } },
        { type: 'blank', spacing: 300 },
        { type: 'signatureBlock', lines: ['Name: {{signatoryName}}', 'Designation: {{signatoryDesignation}}', 'DIN: {{signatoryDin}}', 'PAN: {{signatoryPan}}', 'For: {{entityName}}'], style: {} }
    ],

    pvt_appointment: [
        { type: 'text', content: '{{entityName}}', style: { bold: true, center: true, size: 28 } },
        { type: 'text', content: 'CIN: {{cin}}', style: { center: true, size: 24 } },
        { type: 'text', content: 'Registered Office: {{registeredAddress}}', style: { center: true, size: 24 } },
        { type: 'text', content: '_____________________________________________________________________________', style: { center: true, size: 24 } },
        { type: 'blank', spacing: 200 },
        { type: 'heading', content: 'APPOINTMENT LETTER', style: { bold: true, center: true, size: 28, underline: true } },
        { type: 'blank', spacing: 200 },
        { type: 'text', content: 'Date: {{appointmentDate|date}}', style: { size: 24 } },
        { type: 'blank', spacing: 100 },
        { type: 'text', content: 'To,', style: { size: 24 } },
        { type: 'text', content: '{{appointeeName}}', style: { bold: true, size: 24 } },
        { type: 'text', content: '{{appointeeAddress}}', style: { size: 24 } },
        { type: 'blank', spacing: 200 },
        { type: 'text', content: 'Subject: Appointment as {{appointeeDesignation}}', style: { bold: true, size: 24 } },
        { type: 'blank', spacing: 100 },
        { type: 'text', content: 'Dear {{appointeeName}},', style: { size: 24 } },
        { type: 'blank', spacing: 100 },
        { type: 'text', content: 'We are pleased to inform you that the Board of Directors of {{entityName}} has, at its meeting held on {{appointmentDate|date}}, appointed you as {{appointeeDesignation}} of the Company with effect from {{appointmentDate|date}}.', style: { size: 24 } },
        { type: 'blank', spacing: 100 },
        { type: 'text', content: 'Your appointment is subject to the provisions of the Companies Act, 2013 and the Articles of Association of the Company.', style: { size: 24 } },
        { type: 'blank', spacing: 100 },
        { type: 'text', content: 'Your remuneration shall be {{appointeeRemuneration}} as approved by the Board.', style: { size: 24 } },
        { type: 'blank', spacing: 100 },
        { type: 'text', content: 'We look forward to your valuable contribution to the Company.', style: { size: 24 } },
        { type: 'blank', spacing: 300 },
        { type: 'text', content: 'Yours faithfully,', style: { size: 24 } },
        { type: 'text', content: 'For {{entityName}}', style: { bold: true, size: 24 } },
        { type: 'signatureBlock', lines: ['____________________________', 'Authorized Signatory'], style: {} }
    ],

    pvt_resignation: [
        { type: 'heading', content: 'RESIGNATION LETTER', style: { bold: true, center: true, size: 28, underline: true } },
        { type: 'blank', spacing: 200 },
        { type: 'text', content: 'Date: {{resignationDate|date}}', style: { size: 24 } },
        { type: 'blank', spacing: 100 },
        { type: 'text', content: 'To,', style: { size: 24 } },
        { type: 'text', content: 'The Board of Directors,', style: { size: 24 } },
        { type: 'text', content: '{{entityName}}', style: { bold: true, size: 24 } },
        { type: 'text', content: '{{registeredAddress}}', style: { size: 24 } },
        { type: 'blank', spacing: 200 },
        { type: 'text', content: 'Subject: Resignation from the post of {{resigneeDesignation}}', style: { bold: true, size: 24 } },
        { type: 'blank', spacing: 100 },
        { type: 'text', content: 'Respected Members of the Board,', style: { size: 24 } },
        { type: 'blank', spacing: 100 },
        { type: 'text', content: 'I, {{resigneeName}} (DIN: {{resigneeDin}}), hereby tender my resignation from the post of {{resigneeDesignation}} of {{entityName}} (CIN: {{cin}}) with effect from {{effectiveDate|date}}.', style: { size: 24 } },
        { type: 'blank', spacing: 100 },
        { type: 'text', content: 'Reason: {{resignationReason}}', style: { size: 24 } },
        { type: 'blank', spacing: 100 },
        { type: 'text', content: 'I confirm that there are no other material reasons for my resignation other than those mentioned above.', style: { size: 24 } },
        { type: 'blank', spacing: 100 },
        { type: 'text', content: 'I request you to kindly accept my resignation and take it on record at the earliest.', style: { size: 24 } },
        { type: 'blank', spacing: 300 },
        { type: 'text', content: 'Yours faithfully,', style: { size: 24 } },
        { type: 'signatureBlock', lines: ['____________________________', 'Name: {{resigneeName}}', 'DIN: {{resigneeDin}}'], style: {} }
    ],

    pvt_board_resolution: [
        { type: 'text', content: '{{entityName}}', style: { bold: true, center: true, size: 28 } },
        { type: 'text', content: 'CIN: {{cin}}', style: { center: true, size: 24 } },
        { type: 'text', content: 'Registered Office: {{registeredAddress}}', style: { center: true, size: 24 } },
        { type: 'text', content: '_____________________________________________________________________________', style: { center: true, size: 24 } },
        { type: 'blank', spacing: 200 },
        { type: 'heading', content: 'CERTIFIED TRUE COPY OF THE RESOLUTION', style: { bold: true, center: true, size: 26, underline: true } },
        { type: 'blank', spacing: 200 },
        { type: 'text', content: 'Passed at the Meeting of the Board of Directors of {{entityName}} held on {{resolutionDate|date}} at {{meetingTime}} at {{meetingPlace}}.', style: { size: 24 } },
        { type: 'blank', spacing: 200 },
        { type: 'text', content: 'Subject: {{resolutionSubject}}', style: { bold: true, size: 24 } },
        { type: 'blank', spacing: 100 },
        { type: 'text', content: '{{resolutionText}}', style: { bold: true, size: 24 } },
        { type: 'blank', spacing: 100 },
        { type: 'text', content: 'FURTHER RESOLVED THAT any one Director of the Company be and is hereby authorized to do all such acts, deeds, matters, and things as may be necessary, proper, or expedient for giving effect to the above resolution.', style: { size: 24 } },
        { type: 'blank', spacing: 300 },
        { type: 'text', content: 'For {{entityName}}', style: { bold: true, size: 24 } },
        { type: 'signatureBlock', lines: ['____________________________', '{{chairpersonName}}', 'Chairperson', 'Date: {{resolutionDate|date}}'], style: {} }
    ],

    // ══════════════════════════════════════════
    //  LLP TEMPLATES
    // ══════════════════════════════════════════

    llp_consent: [
        { type: 'heading', content: 'CONSENT TO ACT AS DESIGNATED PARTNER', style: { bold: true, center: true, size: 28, underline: true } },
        { type: 'text', content: '(Pursuant to Section 7(1) of the Limited Liability Partnership Act, 2008)', style: { italics: true, center: true, size: 22 } },
        { type: 'blank', spacing: 200 },
        { type: 'text', content: 'Date: {{consentDate|date}}', style: { size: 24 } },
        { type: 'blank', spacing: 100 },
        { type: 'text', content: 'To,', style: { size: 24 } },
        { type: 'text', content: '{{entityName}} LLP', style: { bold: true, size: 24 } },
        { type: 'text', content: '{{registeredAddress}}', style: { size: 24 } },
        { type: 'blank', spacing: 200 },
        { type: 'text', content: 'I, {{partnerName}}, bearing DPIN {{partnerDpin}}, PAN {{partnerPan}} and Aadhar No. {{partnerAadhar}}, residing at {{partnerAddress}}, hereby give my consent to act as a Designated Partner of {{entityName}} LLP (LLPIN: {{llpin}}).', style: { size: 24 } },
        { type: 'blank', spacing: 100 },
        { type: 'text', content: 'I hereby declare that:', style: { size: 24 } },
        { type: 'text', content: '(a) I am not disqualified from being appointed as a Designated Partner under the LLP Act, 2008.', style: { size: 24 } },
        { type: 'text', content: '(b) I have obtained a valid Designated Partner Identification Number (DPIN).', style: { size: 24 } },
        { type: 'text', content: '(c) I consent to act as Designated Partner and agree to be bound by the provisions of the LLP Agreement and the LLP Act, 2008.', style: { size: 24 } },
        { type: 'blank', spacing: 300 },
        { type: 'text', content: 'Yours faithfully,', style: { size: 24 } },
        { type: 'signatureBlock', lines: ['____________________________', 'Name: {{partnerName}}', 'DPIN: {{partnerDpin}}', 'PAN: {{partnerPan}}'], style: {} }
    ],

    llp_noc: [
        { type: 'heading', content: 'NO OBJECTION CERTIFICATE', style: { bold: true, center: true, size: 32, underline: true } },
        { type: 'blank', spacing: 200 },
        { type: 'text', content: 'Date: {{nocDate|date}}', style: { size: 24 } },
        { type: 'text', content: 'Place: {{nocPlace}}', style: { size: 24 } },
        { type: 'blank', spacing: 200 },
        { type: 'text', content: 'To Whom So Ever It May Concern', style: { bold: true, size: 26 } },
        { type: 'blank', spacing: 200 },
        { type: 'text', content: 'Subject: No Objection Certificate for use of premises as Registered Office of {{entityName}} LLP', style: { size: 24 } },
        { type: 'text', content: 'Reference: LLPIN: {{llpin}}', style: { size: 24 } },
        { type: 'blank', spacing: 100 },
        { type: 'text', content: 'I, {{propertyOwnerName}}, S/o / D/o / W/o {{propertyOwnerRelation}}, bearing PAN {{propertyOwnerPan}} and Aadhar No. {{propertyOwnerAadhar}}, am the owner/authorized occupant of the premises situated at {{propertyAddress}}.', style: { size: 24 } },
        { type: 'blank', spacing: 100 },
        { type: 'text', content: 'I hereby give my No Objection / Consent for {{entityName}} LLP (LLPIN: {{llpin}}) to use the above-mentioned premises as its Registered Office address as per the provisions of the Limited Liability Partnership Act, 2008.', style: { size: 24 } },
        { type: 'blank', spacing: 100 },
        { type: 'text', content: 'I further declare that:', style: { size: 24 } },
        { type: 'text', content: '(a) I am the lawful owner/authorized occupant of the said premises.', style: { size: 24 } },
        { type: 'text', content: '(b) I have given my consent voluntarily and without any coercion.', style: { size: 24 } },
        { type: 'text', content: '(c) This NOC shall remain valid until revoked by me in writing.', style: { size: 24 } },
        { type: 'blank', spacing: 300 },
        { type: 'text', content: 'Yours faithfully,', style: { size: 24 } },
        { type: 'signatureBlock', lines: ['____________________________', 'Name: {{propertyOwnerName}}', 'PAN: {{propertyOwnerPan}}', 'Aadhar: {{propertyOwnerAadhar}}', '(Property Owner / Authorized Occupant)'], style: {} }
    ],

    llp_subscriber: [
        { type: 'heading', content: 'SUBSCRIBER SHEET', style: { bold: true, center: true, size: 28, underline: true } },
        { type: 'text', content: '(For incorporation of Limited Liability Partnership)', style: { italics: true, center: true, size: 22 } },
        { type: 'blank', spacing: 200 },
        { type: 'text', content: 'LLP Name: {{entityName}} LLP', style: { size: 24 } },
        { type: 'text', content: 'Date: {{subscriberDate|date}}', style: { size: 24 } },
        { type: 'blank', spacing: 200 },
        { type: 'text', content: 'We, the undersigned persons, do hereby subscribe our names to this LLP and agree to form a Limited Liability Partnership under the Limited Liability Partnership Act, 2008.', style: { size: 24 } },
        { type: 'blank', spacing: 200 },
        { type: 'text', content: 'S.No. | Name | DPIN | Address | Contribution (Rs.) | Signature', style: { bold: true, size: 22 } },
        { type: 'text', content: '1. {{directors[0].name}} | {{directors[0].din}} | {{directors[0].address}} | {{contributionAmount}} |', style: { size: 22 } },
        { type: 'text', content: '2. {{directors[1].name}} | {{directors[1].din}} | {{directors[1].address}} | {{contributionAmount}} |', style: { size: 22 } },
        { type: 'blank', spacing: 300 },
        { type: 'text', content: 'Witness:', style: { size: 24 } },
        { type: 'text', content: 'Name: ____________________________', style: { size: 24 } },
        { type: 'text', content: 'Address: ____________________________', style: { size: 24 } },
        { type: 'text', content: 'Signature: ____________________________', style: { size: 24 } },
    ],

    // ══════════════════════════════════════════
    //  AOC-04 TEMPLATES
    // ══════════════════════════════════════════

    aoc_director_report: [
        { type: 'text', content: '{{entityName}}', style: { bold: true, center: true, size: 28 } },
        { type: 'text', content: 'CIN: {{cin}}', style: { center: true, size: 24 } },
        { type: 'text', content: 'Registered Office: {{registeredAddress}}', style: { center: true, size: 24 } },
        { type: 'text', content: '_____________________________________________________________________________', style: { center: true, size: 24 } },
        { type: 'blank', spacing: 200 },
        { type: 'heading', content: "BOARD'S REPORT", style: { bold: true, center: true, size: 28, underline: true } },
        { type: 'blank', spacing: 200 },
        { type: 'text', content: 'To the Members of {{entityName}}', style: { size: 24 } },
        { type: 'blank', spacing: 100 },
        { type: 'text', content: 'Your Directors have pleasure in presenting the Report of the Board of Directors along with the Audited Financial Statements for the financial year ended {{financialYear}}.', style: { size: 24 } },
        { type: 'blank', spacing: 200 },
        { type: 'text', content: '1. FINANCIAL SUMMARY:', style: { bold: true, size: 24 } },
        { type: 'text', content: 'Turnover: Rs. {{turnover}}/-', style: { size: 24 } },
        { type: 'text', content: 'Net Profit / (Loss): Rs. {{netProfit}}/-', style: { size: 24 } },
        { type: 'blank', spacing: 100 },
        { type: 'text', content: '2. DIVIDEND:', style: { bold: true, size: 24 } },
        { type: 'text', content: '{{dividendRemarks}}', style: { size: 24 } },
        { type: 'blank', spacing: 100 },
        { type: 'text', content: '3. STATE OF COMPANY AFFAIRS:', style: { bold: true, size: 24 } },
        { type: 'text', content: 'The Company is carrying on its business activities and the state of affairs of the Company is satisfactory.', style: { size: 24 } },
        { type: 'blank', spacing: 100 },
        { type: 'text', content: '4. CHANGE IN NATURE OF BUSINESS:', style: { bold: true, size: 24 } },
        { type: 'text', content: 'There has been no change in the nature of business of the Company during the year.', style: { size: 24 } },
        { type: 'blank', spacing: 100 },
        { type: 'text', content: '5. DIRECTORS:', style: { bold: true, size: 24 } },
        { type: 'text', content: 'The composition of the Board of Directors is in accordance with the provisions of the Companies Act, 2013.', style: { size: 24 } },
        { type: 'blank', spacing: 100 },
        { type: 'text', content: '6. AUDITORS:', style: { bold: true, size: 24 } },
        { type: 'text', content: 'M/s {{auditorName}} (Firm Reg. No. {{auditorRegNo}}), Chartered Accountants, have been appointed as Statutory Auditors of the Company.', style: { size: 24 } },
        { type: 'blank', spacing: 100 },
        { type: 'text', content: "7. DIRECTORS' RESPONSIBILITY STATEMENT:", style: { bold: true, size: 24 } },
        { type: 'text', content: 'Your Directors confirm that:', style: { size: 24 } },
        { type: 'text', content: '(a) In preparation of the annual accounts, applicable accounting standards have been followed.', style: { size: 24 } },
        { type: 'text', content: '(b) Accounting policies have been selected and applied consistently.', style: { size: 24 } },
        { type: 'text', content: '(c) Judgements and estimates are reasonable and prudent.', style: { size: 24 } },
        { type: 'text', content: '(d) Applicable accounting standards have been followed.', style: { size: 24 } },
        { type: 'text', content: '(e) Internal financial controls are adequate and operating effectively.', style: { size: 24 } },
        { type: 'text', content: '(f) Systems to ensure compliance with laws are adequate and operating effectively.', style: { size: 24 } },
        { type: 'blank', spacing: 100 },
        { type: 'text', content: '8. ACKNOWLEDGEMENTS:', style: { bold: true, size: 24 } },
        { type: 'text', content: 'Your Directors wish to express their grateful appreciation for the assistance and cooperation received from the banks, government authorities, customers, and other stakeholders.', style: { size: 24 } },
        { type: 'blank', spacing: 200 },
        { type: 'text', content: 'For and on behalf of the Board of Directors of {{entityName}}', style: { bold: true, size: 24 } },
        { type: 'blank', spacing: 200 },
        { type: 'signatureBlock', lines: ['____________________________', 'Director', 'DIN: ___________'], style: {} },
        { type: 'blank', spacing: 100 },
        { type: 'signatureBlock', lines: ['____________________________', 'Director', 'DIN: ___________'], style: {} },
        { type: 'blank', spacing: 100 },
        { type: 'text', content: 'Place: {{state}}', style: { size: 24 } },
        { type: 'text', content: 'Date: {{reportDate|date}}', style: { size: 24 } },
    ],

    aoc_auditor_report: [
        { type: 'heading', content: "INDEPENDENT AUDITOR'S REPORT", style: { bold: true, center: true, size: 28, underline: true } },
        { type: 'blank', spacing: 200 },
        { type: 'text', content: 'To the Members of {{entityName}}', style: { size: 24 } },
        { type: 'blank', spacing: 200 },
        { type: 'text', content: 'Report on the Audit of the Financial Statements', style: { bold: true, underline: true, size: 24 } },
        { type: 'blank', spacing: 200 },
        { type: 'text', content: 'Opinion:', style: { bold: true, size: 24 } },
        { type: 'text', content: 'We have audited the accompanying financial statements of {{entityName}} (CIN: {{cin}}), which comprise the Balance Sheet as at March 31, the Statement of Profit and Loss, and the Cash Flow Statement for the year then ended, and notes to the financial statements for the financial year {{financialYear}}.', style: { size: 24 } },
        { type: 'blank', spacing: 100 },
        { type: 'text', content: 'In our opinion and to the best of our information and according to the explanations given to us, the aforesaid financial statements give the information required by the Companies Act, 2013 in the manner so required and give a true and fair view in conformity with the Accounting Standards prescribed under Section 133 of the Act.', style: { size: 24 } },
        { type: 'blank', spacing: 100 },
        { type: 'text', content: 'Basis for Opinion:', style: { bold: true, size: 24 } },
        { type: 'text', content: 'We conducted our audit in accordance with the Standards on Auditing (SAs) specified under Section 143(10) of the Companies Act, 2013.', style: { size: 24 } },
        { type: 'blank', spacing: 100 },
        { type: 'text', content: "Management's Responsibility for the Financial Statements:", style: { bold: true, size: 24 } },
        { type: 'text', content: "The Company's Board of Directors is responsible for the matters stated in Section 134(5) of the Companies Act, 2013 with respect to the preparation of these financial statements.", style: { size: 24 } },
        { type: 'blank', spacing: 100 },
        { type: 'text', content: "Auditor's Responsibility:", style: { bold: true, size: 24 } },
        { type: 'text', content: 'Our responsibility is to express an opinion on these financial statements based on our audit.', style: { size: 24 } },
        { type: 'blank', spacing: 300 },
        { type: 'text', content: 'For {{auditorName}}', style: { bold: true, size: 24 } },
        { type: 'text', content: 'Chartered Accountants', style: { size: 24 } },
        { type: 'text', content: 'Firm Registration No.: {{auditorRegNo}}', style: { size: 24 } },
        { type: 'signatureBlock', lines: ['____________________________', 'Partner', 'Membership No.: {{auditorMembershipNo}}', 'Place: {{auditorPlace}}', 'Date: {{reportDate|date}}'], style: {} }
    ],

    // ══════════════════════════════════════════
    //  ORGANISATION DSC TEMPLATES
    // ══════════════════════════════════════════

    dsc_auth_letter: [
        { type: 'heading', content: 'AUTHORIZATION LETTER FOR DIGITAL SIGNATURE CERTIFICATE (DSC)', style: { bold: true, center: true, size: 26, underline: true } },
        { type: 'blank', spacing: 200 },
        { type: 'text', content: 'Date: {{dscDate|date}}', style: { size: 24 } },
        { type: 'blank', spacing: 200 },
        { type: 'text', content: 'To Whom So Ever It May Concern', style: { bold: true, size: 26 } },
        { type: 'blank', spacing: 200 },
        { type: 'text', content: 'This is to certify that {{dscHolderName}}, {{dscHolderDesignation}} of {{entityName}} (PAN: {{dscHolderPan}}), is hereby authorized to use the Digital Signature Certificate (DSC) of the organization for the purpose of {{dscPurpose}}.', style: { size: 24 } },
        { type: 'blank', spacing: 100 },
        { type: 'text', content: 'The said person is authorized to digitally sign all documents, forms, applications, and returns that may be required to be filed electronically with the concerned authorities.', style: { size: 24 } },
        { type: 'blank', spacing: 100 },
        { type: 'text', content: 'This authorization is valid until revoked in writing by the organization.', style: { size: 24 } },
        { type: 'blank', spacing: 300 },
        { type: 'text', content: 'For {{entityName}}', style: { bold: true, size: 24 } },
        { type: 'signatureBlock', lines: ['____________________________', 'Authorized Signatory', 'Date: {{dscDate|date}}'], style: {} }
    ],

    // ══════════════════════════════════════════
    //  FSSAI TEMPLATES
    // ══════════════════════════════════════════

    fssai_declaration: [
        { type: 'heading', content: 'DECLARATION', style: { bold: true, center: true, size: 28, underline: true } },
        { type: 'text', content: '(For FSSAI Registration / License)', style: { italics: true, center: true, size: 22 } },
        { type: 'blank', spacing: 200 },
        { type: 'text', content: 'Date: {{declarationDate|date}}', style: { size: 24 } },
        { type: 'blank', spacing: 200 },
        { type: 'text', content: 'I/We, {{declarantName}}, {{declarantDesignation}} of {{entityName}}, do hereby declare that:', style: { size: 24 } },
        { type: 'blank', spacing: 100 },
        { type: 'text', content: '1. The information provided in the application for FSSAI Registration/License is true and correct to the best of my knowledge and belief.', style: { size: 24 } },
        { type: 'text', content: '2. The food business operated under the name "{{entityName}}" is engaged in {{foodCategory}}.', style: { size: 24 } },
        { type: 'text', content: '3. The food products manufactured/sold/served by us comply with the Food Safety and Standards Act, 2006 and Rules/Regulations made thereunder.', style: { size: 24 } },
        { type: 'text', content: '4. We shall maintain proper records and registers as required under the Act.', style: { size: 24 } },
        { type: 'text', content: '5. We shall not employ any person who is suffering from any communicable disease.', style: { size: 24 } },
        { type: 'text', content: '6. We shall ensure cleanliness and hygiene in the food establishment at all times.', style: { size: 24 } },
        { type: 'blank', spacing: 300 },
        { type: 'signatureBlock', lines: ['____________________________', 'Name: {{declarantName}}', 'Designation: {{declarantDesignation}}', 'For: {{entityName}}', 'FSSAI License No.: {{fssaiLicenseNo}}', 'Date: {{declarationDate|date}}'], style: {} }
    ],

    fssai_affidavit: [
        { type: 'heading', content: 'AFFIDAVIT', style: { bold: true, center: true, size: 28, underline: true } },
        { type: 'text', content: '(For FSSAI Registration / License Application)', style: { italics: true, center: true, size: 22 } },
        { type: 'blank', spacing: 200 },
        { type: 'text', content: 'I, {{affiantName}}, {{affiantDesignation}} of {{entityName}}, residing at {{affiantAddress}}, do hereby solemnly affirm and declare as under:', style: { size: 24 } },
        { type: 'blank', spacing: 100 },
        { type: 'text', content: '1. That I am the {{affiantDesignation}} of {{entityName}} and competent to swear this affidavit.', style: { size: 24 } },
        { type: 'text', content: '2. That the food business establishment complies with all food safety and hygiene requirements.', style: { size: 24 } },
        { type: 'text', content: '3. That the premises used for food business are clean and hygienic.', style: { size: 24 } },
        { type: 'text', content: '4. That all food handlers employed have been medically examined and are free from communicable diseases.', style: { size: 24 } },
        { type: 'text', content: '5. That the information provided in the FSSAI application is true, correct, and complete.', style: { size: 24 } },
        { type: 'text', content: '6. That I shall abide by all provisions of the Food Safety and Standards Act, 2006.', style: { size: 24 } },
        { type: 'blank', spacing: 200 },
        { type: 'text', content: 'I solemnly declare that the above statements are true and correct to the best of my knowledge and belief.', style: { size: 24 } },
        { type: 'blank', spacing: 200 },
        { type: 'text', content: 'VERIFICATION', style: { bold: true, size: 24 } },
        { type: 'text', content: 'Verified at {{affidavitPlace}} on this {{affidavitDate|date}} that the contents of the above affidavit are true and correct.', style: { size: 24 } },
        { type: 'blank', spacing: 300 },
        { type: 'signatureBlock', lines: ['____________________________', 'Deponent', '{{affiantName}}'], style: {} }
    ],

    fssai_self_declaration: [
        { type: 'heading', content: 'SELF DECLARATION', style: { bold: true, center: true, size: 28, underline: true } },
        { type: 'text', content: '(For FSSAI Compliance)', style: { italics: true, center: true, size: 22 } },
        { type: 'blank', spacing: 200 },
        { type: 'text', content: 'Date: {{declarationDate|date}}', style: { size: 24 } },
        { type: 'blank', spacing: 200 },
        { type: 'text', content: 'I/We, {{declarantName}}, {{declarantDesignation}} of {{entityName}}, FSSAI License/Registration No. {{fssaiLicenseNo}}, located at {{businessAddress}}, do hereby declare that:', style: { size: 24 } },
        { type: 'blank', spacing: 100 },
        { type: 'text', content: '1. The food business operated by us meets the requirements of the Food Safety and Standards Act, 2006 and all applicable regulations.', style: { size: 24 } },
        { type: 'text', content: '2. We maintain proper food safety management systems and hygiene practices in our establishment.', style: { size: 24 } },
        { type: 'text', content: '3. All food products manufactured/stored/sold/served comply with the prescribed standards.', style: { size: 24 } },
        { type: 'text', content: '4. We maintain proper records of food purchase, sale, and quality control.', style: { size: 24 } },
        { type: 'text', content: '5. We ensure proper training of food handlers in food safety and hygiene.', style: { size: 24 } },
        { type: 'blank', spacing: 300 },
        { type: 'signatureBlock', lines: ['____________________________', 'Name: {{declarantName}}', 'Designation: {{declarantDesignation}}', 'For: {{entityName}}', 'Date: {{declarationDate|date}}'], style: {} }
    ],

    fssai_fsms: [
        { type: 'heading', content: 'FOOD SAFETY MANAGEMENT SYSTEM (FSMS) DECLARATION', style: { bold: true, center: true, size: 26, underline: true } },
        { type: 'blank', spacing: 200 },
        { type: 'text', content: 'Date: {{declarationDate|date}}', style: { size: 24 } },
        { type: 'blank', spacing: 200 },
        { type: 'text', content: 'I/We, {{declarantName}}, {{declarantDesignation}} of {{entityName}}, do hereby declare that our food business establishment has implemented a Food Safety Management System as per Schedule 4 of the Food Safety and Standards (Licensing and Registration of Food Businesses) Regulations, 2011.', style: { size: 24 } },
        { type: 'blank', spacing: 100 },
        { type: 'text', content: 'The FSMS includes:', style: { bold: true, size: 24 } },
        { type: 'text', content: '1. General requirements on hygienic and sanitary practices to be followed by all food business operators.', style: { size: 24 } },
        { type: 'text', content: '2. General hygienic and sanitary practices to be followed by petty food operators.', style: { size: 24 } },
        { type: 'text', content: '3. Specific hygienic and sanitary practices to be followed for the specific type of food business.', style: { size: 24 } },
        { type: 'text', content: '4. Good Manufacturing Practices (GMP) and Good Hygienic Practices (GHP).', style: { size: 24 } },
        { type: 'text', content: '5. Hazard Analysis and Critical Control Point (HACCP) system where applicable.', style: { size: 24 } },
        { type: 'blank', spacing: 200 },
        { type: 'text', content: 'We undertake to maintain proper documentation and records of our food safety management system.', style: { size: 24 } },
        { type: 'blank', spacing: 300 },
        { type: 'signatureBlock', lines: ['____________________________', 'Name: {{declarantName}}', 'Designation: {{declarantDesignation}}', 'For: {{entityName}}', 'FSSAI License No.: {{fssaiLicenseNo}}', 'Date: {{declarationDate|date}}'], style: {} }
    ],

    // ══════════════════════════════════════════
    //  MCA FORMS TEMPLATES
    // ══════════════════════════════════════════

    mca_form03: [
        { type: 'heading', content: 'FORM MGT-14 / FORM-03', style: { bold: true, center: true, size: 28, underline: true } },
        { type: 'text', content: '(Filing of Resolutions and Agreements)', style: { italics: true, center: true, size: 22 } },
        { type: 'blank', spacing: 200 },
        { type: 'text', content: 'Company Name: {{entityName}}', style: { bold: true, size: 24 } },
        { type: 'text', content: 'CIN: {{cin}}', style: { size: 24 } },
        { type: 'text', content: 'Registered Office: {{registeredAddress}}', style: { size: 24 } },
        { type: 'blank', spacing: 200 },
        { type: 'text', content: 'CERTIFIED TRUE COPY OF THE RESOLUTION', style: { bold: true, center: true, size: 26 } },
        { type: 'blank', spacing: 200 },
        { type: 'text', content: 'Passed at the Board Meeting / General Meeting held on {{resolutionDate|date}} at {{meetingPlace}}.', style: { size: 24 } },
        { type: 'blank', spacing: 200 },
        { type: 'text', content: 'Subject: {{resolutionSubject}}', style: { bold: true, size: 24 } },
        { type: 'blank', spacing: 100 },
        { type: 'text', content: '{{resolutionText}}', style: { bold: true, size: 24 } },
        { type: 'blank', spacing: 200 },
        { type: 'text', content: 'I hereby certify that the above is a true copy of the resolution passed at the meeting of the Board of Directors / Members of the Company.', style: { size: 24 } },
        { type: 'blank', spacing: 300 },
        { type: 'text', content: 'For {{entityName}}', style: { bold: true, size: 24 } },
        { type: 'signatureBlock', lines: ['____________________________', '{{fullName}}', 'Director / Company Secretary', 'Date: {{resolutionDate|date}}'], style: {} }
    ],

    mca_form15: [
        { type: 'heading', content: 'DECLARATION OF COMPLIANCE', style: { bold: true, center: true, size: 28, underline: true } },
        { type: 'text', content: '(Pursuant to Section 7(1)(b) of the Companies Act, 2013 - INC-15)', style: { italics: true, center: true, size: 22 } },
        { type: 'blank', spacing: 200 },
        { type: 'text', content: 'I, {{declarantName}}, an advocate / a chartered accountant / a cost accountant / a company secretary in whole-time practice, do hereby declare that all the requirements of the Companies Act, 2013 and the rules made thereunder in respect of incorporation of {{entityName}} have been complied with.', style: { size: 24 } },
        { type: 'blank', spacing: 100 },
        { type: 'text', content: 'I further declare that:', style: { size: 24 } },
        { type: 'text', content: '1. The Memorandum and Articles of Association have been properly drawn up and stamped.', style: { size: 24 } },
        { type: 'text', content: '2. All requirements relating to the registration of the company have been complied with.', style: { size: 24 } },
        { type: 'text', content: '3. The company is being formed for a lawful purpose.', style: { size: 24 } },
        { type: 'text', content: '4. All persons named as subscribers are competent to do so.', style: { size: 24 } },
        { type: 'text', content: '5. All information given in the incorporation documents is correct and complete.', style: { size: 24 } },
        { type: 'blank', spacing: 300 },
        { type: 'signatureBlock', lines: ['____________________________', 'Name: {{declarantName}}', 'Membership No.: {{declarantMembershipNo}}', 'Firm/Practice: {{declarantFirm}}', 'Date: {{declarationDate|date}}'], style: {} }
    ],

    // ══════════════════════════════════════════
    //  LABOUR TEMPLATES
    // ══════════════════════════════════════════

    llp_revised_agreement: [
        { type: 'heading', content: 'REVISED LIMITED LIABILITY PARTNERSHIP AGREEMENT', style: { bold: true, center: true, size: 28, underline: true } },
        { type: 'blank', spacing: 300 },
        { type: 'text', content: 'This Revised LLP Agreement is made and executed on this {{agreementDate|date}} at {{agreementPlace}}', style: { size: 24 } },
        { type: 'blank', spacing: 100 },
        { type: 'text', content: 'In supersession of the earlier LLP Agreement dated {{originalAgreementDate|date}}, the partners of {{entityName}} LLP (LLPIN: {{llpin}}) have mutually agreed to revise the LLP Agreement as follows:', style: { size: 24 } },
        { type: 'blank', spacing: 100 },
        { type: 'text', content: 'Reason for Revision: {{revisionReason}}', style: { bold: true, size: 24 } },
        { type: 'blank', spacing: 200 },
        { type: 'text', content: 'BETWEEN', style: { bold: true, center: true, size: 24 } },
        { type: 'blank', spacing: 100 },
        { type: 'text', content: '1. {{partner1Name}} (DPIN: {{partner1Dpin}}), residing at {{partner1Address}} (hereinafter referred to as "First Designated Partner")', style: { size: 24 } },
        { type: 'blank', spacing: 100 },
        { type: 'text', content: '2. {{partner2Name}} (DPIN: {{partner2Dpin}}), residing at {{partner2Address}} (hereinafter referred to as "Second Designated Partner")', style: { size: 24 } },
        { type: 'blank', spacing: 200 },
        { type: 'text', content: 'NOW THIS AGREEMENT WITNESSETH AS FOLLOWS:', style: { bold: true, size: 24 } },
        { type: 'blank', spacing: 100 },
        { type: 'text', content: '1. NAME OF LLP:', style: { bold: true, size: 24 } },
        { type: 'text', content: 'The name of the LLP shall be "{{entityName}} LLP".', style: { size: 24 } },
        { type: 'blank', spacing: 100 },
        { type: 'text', content: '2. REGISTERED OFFICE:', style: { bold: true, size: 24 } },
        { type: 'text', content: 'The registered office of the LLP shall be at {{registeredAddress}}.', style: { size: 24 } },
        { type: 'blank', spacing: 100 },
        { type: 'text', content: '3. NATURE OF BUSINESS:', style: { bold: true, size: 24 } },
        { type: 'text', content: '{{businessNature}}', style: { size: 24 } },
        { type: 'blank', spacing: 100 },
        { type: 'text', content: '4. CAPITAL CONTRIBUTION:', style: { bold: true, size: 24 } },
        { type: 'text', content: '{{partner1Name}}: Rs. {{partner1Contribution}}/- (Rupees {{partner1Contribution|words}} Only)', style: { size: 24 } },
        { type: 'text', content: '{{partner2Name}}: Rs. {{partner2Contribution}}/- (Rupees {{partner2Contribution|words}} Only)', style: { size: 24 } },
        { type: 'blank', spacing: 100 },
        { type: 'text', content: '5. PROFIT AND LOSS SHARING RATIO:', style: { bold: true, size: 24 } },
        { type: 'text', content: '{{partner1Name}}: {{partner1ProfitShare}}%', style: { size: 24 } },
        { type: 'text', content: '{{partner2Name}}: {{partner2ProfitShare}}%', style: { size: 24 } },
        { type: 'blank', spacing: 100 },
        { type: 'text', content: '6. MANAGEMENT:', style: { bold: true, size: 24 } },
        { type: 'text', content: 'The management and conduct of the business of the LLP shall be carried out by mutual consent of all the Designated Partners.', style: { size: 24 } },
        { type: 'blank', spacing: 100 },
        { type: 'text', content: '7. BANK ACCOUNT:', style: { bold: true, size: 24 } },
        { type: 'text', content: 'The LLP shall operate bank account(s) in the name of the LLP. The bank account shall be operated jointly/severally by the Designated Partners.', style: { size: 24 } },
        { type: 'blank', spacing: 100 },
        { type: 'text', content: '8. BOOKS OF ACCOUNTS:', style: { bold: true, size: 24 } },
        { type: 'text', content: 'The LLP shall maintain proper books of accounts at its registered office as required under the LLP Act, 2008.', style: { size: 24 } },
        { type: 'blank', spacing: 100 },
        { type: 'text', content: '9. DISPUTE RESOLUTION:', style: { bold: true, size: 24 } },
        { type: 'text', content: 'Any dispute or difference arising between the partners shall be referred to arbitration in accordance with the Arbitration and Conciliation Act, 1996.', style: { size: 24 } },
        { type: 'blank', spacing: 100 },
        { type: 'text', content: '10. GENERAL:', style: { bold: true, size: 24 } },
        { type: 'text', content: 'All other matters not specifically covered under this Agreement shall be governed by the provisions of the Limited Liability Partnership Act, 2008 and the rules made thereunder.', style: { size: 24 } },
        { type: 'blank', spacing: 200 },
        { type: 'text', content: 'IN WITNESS WHEREOF, the parties have set and subscribed their hands on the day, month, and year first above written.', style: { size: 24 } },
        { type: 'blank', spacing: 300 },
        { type: 'signatureBlock', lines: ['FIRST DESIGNATED PARTNER', '', 'Signature: ____________________', 'Name: {{partner1Name}}', 'DPIN: {{partner1Dpin}}'], style: {} },
        { type: 'blank', spacing: 200 },
        { type: 'signatureBlock', lines: ['SECOND DESIGNATED PARTNER', '', 'Signature: ____________________', 'Name: {{partner2Name}}', 'DPIN: {{partner2Dpin}}'], style: {} },
        { type: 'blank', spacing: 300 },
        { type: 'text', content: 'WITNESS:', style: { bold: true, size: 24 } },
        { type: 'signatureBlock', lines: ['Name: {{witnessName}}', 'Address: {{witnessAddress}}', 'Signature: ____________________'], style: {} },
    ],

    mca_dir2: [
        { type: 'heading', content: 'FORM DIR-2', style: { bold: true, center: true, size: 32 } },
        { type: 'text', content: 'Consent to Act as a Director of a Company', style: { bold: true, center: true, size: 26 } },
        { type: 'text', content: '[Pursuant to Section 152(5) of the Companies Act, 2013 and Rule 8 of the Companies (Appointment and Qualification of Directors) Rules, 2014]', style: { center: true, size: 20 } },
        { type: 'blank', spacing: 300 },
        { type: 'text', content: 'To,', style: { bold: true, size: 24 } },
        { type: 'text', content: 'The Board of Directors', style: { bold: true, size: 24 } },
        { type: 'text', content: '{{entityName}}', style: { bold: true, size: 24 } },
        { type: 'text', content: '{{address}}', style: { size: 24 } },
        { type: 'blank', spacing: 200 },
        { type: 'text', content: 'Subject: Consent to act as {{directorDesignation}} of the Company', style: { bold: true, size: 24 } },
        { type: 'blank', spacing: 200 },
        { type: 'text', content: 'Dear Sir/Madam,', style: { size: 24 } },
        { type: 'blank', spacing: 100 },
        { type: 'text', content: 'I, {{directorName}}, son/daughter of {{directorFatherName}}, resident of {{directorAddress}}, bearing DIN {{din}} and PAN {{directorPAN}}, hereby give my consent to act as {{directorDesignation}} of {{entityName}} with effect from {{appointmentDate|date}}.', style: { size: 24 } },
        { type: 'blank', spacing: 100 },
        { type: 'text', content: 'I hereby confirm and declare that:', style: { size: 24 } },
        { type: 'blank', spacing: 50 },
        { type: 'text', content: '1. I am not disqualified to act as a Director under Section 164 of the Companies Act, 2013.', style: { size: 24 } },
        { type: 'text', content: '2. I have not been convicted of any offence dealing with related party transactions under Section 188 of the Companies Act, 2013 at any time during the last preceding five years.', style: { size: 24 } },
        { type: 'text', content: '3. I have not been debarred from holding the office of a director by virtue of any SEBI order or any other such authority.', style: { size: 24 } },
        { type: 'text', content: '4. I have not been declared as a person unfit for appointment as a director by any competent court or tribunal.', style: { size: 24 } },
        { type: 'text', content: '5. I am not an undischarged insolvent.', style: { size: 24 } },
        { type: 'text', content: '6. I have not been convicted by a court for any offence involving moral turpitude and sentenced to imprisonment for not less than six months and a period of five years has not elapsed from the date of expiry of the sentence.', style: { size: 24 } },
        { type: 'text', content: '7. I have not been removed as a director of a company under Section 169 of the Act.', style: { size: 24 } },
        { type: 'blank', spacing: 100 },
        { type: 'text', content: 'My details for the purpose of records are as follows:', style: { size: 24 } },
        { type: 'blank', spacing: 100 },
        { type: 'text', content: 'Name: {{directorName}}', style: { size: 24 } },
        { type: 'text', content: "Father's Name: {{directorFatherName}}", style: { size: 24 } },
        { type: 'text', content: 'Date of Birth: {{directorDOB|date}}', style: { size: 24 } },
        { type: 'text', content: 'Nationality: {{directorNationality}}', style: { size: 24 } },
        { type: 'text', content: 'Occupation: {{directorOccupation}}', style: { size: 24 } },
        { type: 'text', content: 'PAN: {{directorPAN}}', style: { size: 24 } },
        { type: 'text', content: 'DIN: {{din}}', style: { size: 24 } },
        { type: 'text', content: 'Residential Address: {{directorAddress}}', style: { size: 24 } },
        { type: 'blank', spacing: 300 },
        { type: 'text', content: 'Yours faithfully,', style: { size: 24 } },
        { type: 'signatureBlock', lines: ['____________________________', 'Name: {{directorName}}', 'DIN: {{din}}', 'Place: {{directorPlace}}', 'Date: {{consentDate|date}}'], style: {} },
    ],

    labour_auth_letter: [
        { type: 'heading', content: 'AUTHORIZATION LETTER', style: { bold: true, center: true, size: 28, underline: true } },
        { type: 'text', content: '(For Labour Department / ESI / PF Registration)', style: { italics: true, center: true, size: 22 } },
        { type: 'blank', spacing: 200 },
        { type: 'text', content: 'Date: {{authDate|date}}', style: { size: 24 } },
        { type: 'blank', spacing: 200 },
        { type: 'text', content: 'To Whom So Ever It May Concern', style: { bold: true, size: 26 } },
        { type: 'blank', spacing: 200 },
        { type: 'text', content: 'Subject: Authorization Letter for {{authPurpose}} of {{entityName}}', style: { size: 24 } },
        { type: 'blank', spacing: 100 },
        { type: 'text', content: 'Respected Sir/Madam,', style: { size: 24 } },
        { type: 'blank', spacing: 100 },
        { type: 'text', content: 'We, {{entityName}}, having its registered office at {{registeredAddress}}, hereby authorize {{authPersonName}}, bearing PAN {{authPersonPan}} and Aadhar No. {{authPersonAadhar}}, to act on our behalf for the purpose of {{authPurpose}}.', style: { size: 24 } },
        { type: 'blank', spacing: 100 },
        { type: 'text', content: 'The authorized person is empowered to:', style: { size: 24 } },
        { type: 'text', content: '1. Apply for registration under the applicable labour laws.', style: { size: 24 } },
        { type: 'text', content: '2. Sign and submit all necessary documents, applications, and declarations.', style: { size: 24 } },
        { type: 'text', content: '3. Represent the company before the concerned authorities.', style: { size: 24 } },
        { type: 'text', content: '4. Do all acts, deeds, and things as may be necessary for the said purpose.', style: { size: 24 } },
        { type: 'blank', spacing: 100 },
        { type: 'text', content: 'This authorization is valid until revoked in writing.', style: { size: 24 } },
        { type: 'blank', spacing: 300 },
        { type: 'text', content: 'Yours faithfully,', style: { size: 24 } },
        { type: 'text', content: 'For {{entityName}}', style: { bold: true, size: 24 } },
        { type: 'signatureBlock', lines: ['____________________________', 'Name: {{fullName}}', 'Designation: Director / Proprietor', 'Date: {{authDate|date}}'], style: {} }
    ],
};
